
package com.ws.samples.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeServer", targetNamespace = "http://sei.samples.ws.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TimeServer {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://sei.samples.ws.com/TimeServer/getTimeAsElapsedRequest", output = "http://sei.samples.ws.com/TimeServer/getTimeAsElapsedResponse")
    public long getTimeAsElapsed();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://sei.samples.ws.com/TimeServer/getTimeAsStringRequest", output = "http://sei.samples.ws.com/TimeServer/getTimeAsStringResponse")
    public String getTimeAsString();

}
