
package com.ws.samples.client.echo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Echo", targetNamespace = "http://sib.samples.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Echo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://sib.samples.ws.com/", className = "com.ws.samples.client.echo.Echo_Type")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://sib.samples.ws.com/", className = "com.ws.samples.client.echo.EchoResponse")
    @Action(input = "http://sib.samples.ws.com/Echo/echoRequest", output = "http://sib.samples.ws.com/Echo/echoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
